CREATE SCHEMA IF NOT EXISTS public;
create schema if not exists TODO_LIST;
drop table TODO_ITEM if exists;
drop table TODO_LIST if exists;
create table TODO_ITEM (id bigint generated by default as identity, deadline timestamp, description varchar(255), name varchar(255), status boolean not null, todo_list_id bigint, primary key (id));
create table TODO_LIST (id bigint generated by default as identity, name varchar(255), primary key (id));
alter table TODO_ITEM add constraint FKteq2m3pydjyfajp6msycpeac3 foreign key (todo_list_id) references TODO_LIST;